metadata:
  platform: rest
language:
  rest:
    target_api_root_dir: docs-ref-autogen
    is_operation_level: true
    use_yaml_schema: true
    use_service_url_group: true
    is_grouped_by_tag: true
    remove_tag_from_operationId: true

toc:
- name: Azure Digital Twins
  href: index.md
- name: Reference
  items:
  - name: Data Plane
    rest:
      url_path: dataplane
      readme:
        source: digital-twins-control/specification/digitaltwins/data-plane/DigitalTwins/readme.md
  - name: Control Plane
    rest:
      url_path: controlplane
      readme:
        source: digital-twins-control/specification/digitaltwins/resource-manager/Microsoft.DigitalTwins/DigitalTwins/readme.md


